#!/usr/bin/env bash
#Configures an Ubuntu machine to install Nginx

apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
